/**
 * 本機開發用假資料
 * 設定 NEXT_PUBLIC_USE_MOCK=true 啟用
 */

import type { MarkerData, RestaurantDetail } from './api';

function picsum(seed: string): string {
  return `picsum/${seed}/600/400`;
}

export const MOCK_MARKERS: MarkerData[] = [
  // ── 台北市 ──────────────────────────────────────────────
  {
    id: 'mock-1',
    name: '阿財豬腳飯',
    slug: 'a-cai-zhu-jiao-fan',
    latitude: 25.0478,
    longitude: 121.5170,
    price_min: 80,
    price_max: 120,
    price_item_name: '豬腳飯',
    price_amount: 80,
    price_reported_at: '2026-04-01T08:00:00Z',
    beggar_index: 4.8,
    beggar_perks: ['免費加飯', '免費湯'],
    categories: ['台式', '便當'],
    meal_types: ['午餐', '晚餐'],
    cuisine_types: ['便當', '中式料理'],
    cover_image_key: picsum('pork-rice'),
    avg_rating: 4.8,
    review_count: 143,
  },
  {
    id: 'mock-2',
    name: '永康牛肉麵',
    slug: 'yong-kang-niu-rou-mian',
    latitude: 25.0322,
    longitude: 121.5298,
    price_min: 150,
    price_max: 250,
    price_item_name: '招牌紅燒牛肉麵',
    price_amount: 180,
    price_reported_at: '2026-03-20T10:00:00Z',
    beggar_index: 3.9,
    beggar_perks: [],
    categories: ['麵食', '台式'],
    meal_types: ['午餐', '晚餐'],
    cuisine_types: ['麵食', '中式料理'],
    cover_image_key: picsum('noodle'),
    avg_rating: 3.9,
    review_count: 87,
  },
  {
    id: 'mock-3',
    name: '師大夜市臭豆腐',
    slug: 'shi-da-ye-shi-chou-dou-fu',
    latitude: 25.0263,
    longitude: 121.5293,
    price_min: 50,
    price_max: 80,
    price_item_name: '脆皮臭豆腐（4塊）',
    price_amount: 55,
    price_reported_at: '2026-04-10T18:00:00Z',
    beggar_index: 4.5,
    beggar_perks: ['免費加泡菜'],
    categories: ['小吃', '夜市'],
    meal_types: ['小吃', '宵夜'],
    cuisine_types: ['中式料理'],
    cover_image_key: picsum('tofu'),
    avg_rating: 4.5,
    review_count: 221,
  },
  {
    id: 'mock-4',
    name: '西門町速食（測試低分）',
    slug: 'xi-men-ding-test',
    latitude: 25.0432,
    longitude: 121.5081,
    price_min: 120,
    price_max: 200,
    price_item_name: '套餐',
    price_amount: 149,
    price_reported_at: null,
    beggar_index: 1.8,
    beggar_perks: [],
    categories: ['速食'],
    meal_types: ['午餐', '晚餐'],
    cuisine_types: ['其他'],
    cover_image_key: null,
    avg_rating: 1.8,
    review_count: 5,
  },
  {
    id: 'mock-5',
    name: '公館素食自助餐',
    slug: 'gong-guan-su-shi',
    latitude: 25.0140,
    longitude: 121.5343,
    price_min: 60,
    price_max: 100,
    price_item_name: '自助餐一盤',
    price_amount: 65,
    price_reported_at: '2026-04-05T12:00:00Z',
    beggar_index: 4.2,
    beggar_perks: ['免費加飯', '免費飲料'],
    categories: ['素食', '自助餐'],
    meal_types: ['午餐'],
    cuisine_types: ['自助餐', '健康餐'],
    cover_image_key: picsum('vege'),
    avg_rating: 4.2,
    review_count: 58,
  },
  {
    id: 'mock-6',
    name: '南機場夜市雞排',
    slug: 'nan-ji-chang-ji-pai',
    latitude: 25.0320,
    longitude: 121.5060,
    price_min: 70,
    price_max: 90,
    price_item_name: '大雞排',
    price_amount: 75,
    price_reported_at: '2026-04-12T19:00:00Z',
    beggar_index: 4.7,
    beggar_perks: [],
    categories: ['炸物', '夜市'],
    meal_types: ['小吃', '宵夜'],
    cuisine_types: ['中式料理'],
    cover_image_key: picsum('chicken'),
    avg_rating: 4.7,
    review_count: 312,
  },
  // cluster 測試：大安區密集
  {
    id: 'mock-7',
    name: '大安路便當店A',
    slug: 'da-an-bian-dang-a',
    latitude: 25.0368,
    longitude: 121.5437,
    price_min: 80,
    price_max: 100,
    price_item_name: '排骨便當',
    price_amount: 85,
    price_reported_at: null,
    beggar_index: 3.5,
    beggar_perks: ['免費加菜'],
    categories: ['便當'],
    meal_types: ['午餐', '晚餐'],
    cuisine_types: ['便當'],
    cover_image_key: null,
    avg_rating: 3.5,
    review_count: 12,
  },
  {
    id: 'mock-8',
    name: '大安路便當店B',
    slug: 'da-an-bian-dang-b',
    latitude: 25.0372,
    longitude: 121.5441,
    price_min: 75,
    price_max: 95,
    price_item_name: '雞腿便當',
    price_amount: 80,
    price_reported_at: null,
    beggar_index: 3.8,
    beggar_perks: [],
    categories: ['便當'],
    meal_types: ['午餐', '晚餐'],
    cuisine_types: ['便當'],
    cover_image_key: null,
    avg_rating: 3.8,
    review_count: 8,
  },
  {
    id: 'mock-9',
    name: '大安路麵店C',
    slug: 'da-an-mian-dian-c',
    latitude: 25.0375,
    longitude: 121.5448,
    price_min: 65,
    price_max: 90,
    price_item_name: '乾麵',
    price_amount: 65,
    price_reported_at: null,
    beggar_index: 4.1,
    beggar_perks: ['自助吧'],
    categories: ['麵食'],
    meal_types: ['午餐', '晚餐'],
    cuisine_types: ['麵食'],
    cover_image_key: null,
    avg_rating: 4.1,
    review_count: 31,
  },
  // ── 新北市 ──────────────────────────────────────────────
  {
    id: 'mock-10',
    name: '板橋早餐王',
    slug: 'ban-qiao-zao-can-wang',
    latitude: 25.0144,
    longitude: 121.4627,
    price_min: 35,
    price_max: 65,
    price_item_name: '蛋餅加蛋',
    price_amount: 40,
    price_reported_at: '2026-04-08T07:30:00Z',
    beggar_index: 4.6,
    beggar_perks: ['免費飲料'],
    categories: ['早餐', '台式'],
    meal_types: ['早餐'],
    cuisine_types: ['中式料理'],
    cover_image_key: picsum('breakfast'),
    avg_rating: 4.6,
    review_count: 189,
  },
  {
    id: 'mock-11',
    name: '永和豆漿大王',
    slug: 'yong-he-dou-jiang',
    latitude: 25.0075,
    longitude: 121.5128,
    price_min: 25,
    price_max: 60,
    price_item_name: '鹹豆漿',
    price_amount: 30,
    price_reported_at: '2026-04-11T06:00:00Z',
    beggar_index: 4.9,
    beggar_perks: ['免費加湯'],
    categories: ['早餐', '豆漿'],
    meal_types: ['早餐'],
    cuisine_types: ['中式料理', '飲品&咖啡'],
    cover_image_key: picsum('soymilk'),
    avg_rating: 4.9,
    review_count: 503,
  },
  // ── 台中市 ──────────────────────────────────────────────
  {
    id: 'mock-12',
    name: '台中一中街雞排',
    slug: 'tai-zhong-ji-pai',
    latitude: 24.1480,
    longitude: 120.6840,
    price_min: 60,
    price_max: 85,
    price_item_name: '脆皮雞排',
    price_amount: 65,
    price_reported_at: '2026-03-28T15:00:00Z',
    beggar_index: 4.4,
    beggar_perks: [],
    categories: ['炸物', '小吃'],
    meal_types: ['小吃'],
    cuisine_types: ['中式料理'],
    cover_image_key: picsum('taichung'),
    avg_rating: 4.4,
    review_count: 76,
  },
  {
    id: 'mock-13',
    name: '逢甲夜市大腸包小腸',
    slug: 'feng-jia-da-chang-bao-xiao-chang',
    latitude: 24.1793,
    longitude: 120.6446,
    price_min: 55,
    price_max: 70,
    price_item_name: '大腸包小腸',
    price_amount: 60,
    price_reported_at: '2026-04-02T20:00:00Z',
    beggar_index: 4.3,
    beggar_perks: [],
    categories: ['小吃', '夜市'],
    meal_types: ['小吃', '宵夜'],
    cuisine_types: ['中式料理'],
    cover_image_key: picsum('fengjia'),
    avg_rating: 4.3,
    review_count: 411,
  },
  // ── 台南市 ──────────────────────────────────────────────
  {
    id: 'mock-14',
    name: '赤崁擔仔麵',
    slug: 'chi-kan-dan-zai-mian',
    latitude: 22.9985,
    longitude: 120.2013,
    price_min: 45,
    price_max: 80,
    price_item_name: '擔仔麵',
    price_amount: 50,
    price_reported_at: '2026-04-09T12:00:00Z',
    beggar_index: 4.7,
    beggar_perks: ['免費加湯'],
    categories: ['麵食', '台式'],
    meal_types: ['午餐', '晚餐', '小吃'],
    cuisine_types: ['麵食', '中式料理'],
    cover_image_key: picsum('tainan'),
    avg_rating: 4.7,
    review_count: 238,
  },
  // ── 高雄市 ──────────────────────────────────────────────
  {
    id: 'mock-15',
    name: '六合夜市烤玉米',
    slug: 'liu-he-ye-shi-kao-yu-mi',
    latitude: 22.6280,
    longitude: 120.3014,
    price_min: 30,
    price_max: 50,
    price_item_name: '烤玉米',
    price_amount: 35,
    price_reported_at: '2026-04-07T21:00:00Z',
    beggar_index: 4.0,
    beggar_perks: [],
    categories: ['小吃', '夜市'],
    meal_types: ['小吃', '宵夜'],
    cuisine_types: ['中式料理'],
    cover_image_key: picsum('kaohsiung'),
    avg_rating: 4.0,
    review_count: 92,
  },
];

export const MOCK_DETAILS: Record<string, RestaurantDetail> = {
  'mock-1': {
    ...MOCK_MARKERS[0],
    address: '台北市大同區迪化街一段21號',
    status: 'active',
    created_at: '2025-11-01T08:00:00Z',
    flag_count: 3,
    reviews: [
      {
        id: 'rv-1',
        rating: 5,
        price_paid: 100,
        comment: '超級好吃！豬腳軟嫩入味，飯又大碗，CP值爆表，強烈推薦！',
        created_at: '2026-03-15T12:30:00Z',
      },
      {
        id: 'rv-2',
        rating: 5,
        price_paid: 90,
        comment: '台北市區內難得的平價美食，老闆人很親切，下次還會再來。',
        created_at: '2026-03-10T18:45:00Z',
      },
      {
        id: 'rv-3',
        rating: 4,
        price_paid: 110,
        comment: '好吃，但午餐時間要排隊，建議避開12點。',
        created_at: '2026-02-28T13:00:00Z',
      },
    ],
  },
};

export function getMockDetail(id: string): RestaurantDetail | null {
  if (MOCK_DETAILS[id]) return MOCK_DETAILS[id];
  const marker = MOCK_MARKERS.find((m) => m.id === id);
  if (!marker) return null;
  return {
    ...marker,
    address: '（測試資料）台灣某處',
    status: 'active',
    created_at: '2025-01-01T00:00:00Z',
    flag_count: 0,
    reviews: [],
  };
}
